alias: "Chore: Do Taxes: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_do_taxes
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_do_taxes
    state: "off"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_do_taxes
  - service: notify.ios_parents
    data:
      title: "Chore: Do Taxes"
      message: "We have done our taxes! Hopefully we get cash monies from the gummint"
  - service: notify.slack_standard
    data:
      message: "The chore 'Do Taxes' has been completed"
