alias: "Chore: Do Taxes: Reset"
initial_state: true
trigger:
  - platform: time
    at: "08:00:00"
condition:
  - condition: template
    value_template: "{{ (now().month == 1) }}" # March
  - condition: template
    value_template: "{{ (now().day == 1) }}" # 1st day of month
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_do_taxes
  - service: notify.slack_standard
    data:
      message: "The chore 'Do Taxes' is due today"
