alias: "Chore: Update Budget: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_update_budget
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_update_budget
    state: "off"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_update_budget
  - service: notify.ios_parents
    data:
      title: "Chore: Update Budget"
      message: "Next month's budget has been set - go buy a yacht!"
  - service: notify.slack_standard
    data:
      message: "The chore 'Update Budget' has been completed"
