alias: "Chore: Have HVAC Serviced: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_have_hvac_serviced
condition:
  - condition: template
    value_template: "{{ (states.input_boolean.chore_have_hvac_serviced.state == 'off') }}"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_have_hvac_serviced
  - service: notify.ios_parents
    data:
      title: "Chore: Have HVAC Serviced"
      message: "Rest easy, the HVAC has been serviced and is in good order"
  - service: notify.slack_standard
    data:
      message: "The chore 'Have HVAC Serviced' has been completed"
