alias: "Chore: Have HVAC Serviced: Reset"
initial_state: true
trigger:
  - platform: time
    at: "08:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: template
    value_template: "{{ (now().month == 9) }}" # September
  - condition: template
    value_template: "{{ (now().day == 1) }}" # First day of the month
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_have_hvac_serviced
  - service: notify.slack_standard
    data:
      message: "The chore 'Have HVAC Serviced' is due today"
