alias: "Chore: Run Affresh In Washing Machine: Reset"
initial_state: true
trigger:
  - platform: time
    at: "08:00:00"
condition:
  - condition: template
    value_template: "{{ (now().day == 15) }}" # Fifteenth day of month
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_run_affresh_in_washing_machine
