alias: "Anniversary: Event 9: Today"
initial_state: true
trigger:
  - platform: time
    at: "09:00:00"
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.automation_milestones
    state: "on"
  - condition: template
    value_template: "{{ (states.input_datetime.anniversary_9.state.split('-')[1:] == (as_timestamp(now()) | timestamp_custom('%m-%d')).split('-')) }}"
action:
  - service: notify.ios_parents
    data:
      title: "Anniversary: {{ states.input_datetime.anniversary_9.attributes.friendly_name }}: Today"
      message: "{{ states.input_datetime.anniversary_9.attributes.friendly_name }} anniversary is today!"
  - service: notify.slack_standard
    data:
      message: "{{ states.input_datetime.anniversary_9.attributes.friendly_name }} anniversary is today!"
