alias: "Notification: August Lock: Battery Level Change"
initial_state: true
trigger:
  - platform: template
    value_template: "{{ ((states.sensor.front_door_lock_battery_level.state | int) < 10) }}"
condition:
  - condition: state
    entity_id: binary_sensor.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "August Lock battery level is less than 10%: {{ states.sensor.front_door_lock_battery_level.state }}%"
