alias: "Notification: August Lock: State Change"
initial_state: true
trigger:
  - platform: state
    entity_id: lock.front_door
    from: "locked"
    to: "unlocked"
  - platform: state
    entity_id: lock.front_door
    from: "unlocked"
    to: "locked"
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "August Lock state changed to '{{ states.lock.front_door.state }}'"
