alias: "Notification: Front Door Lock: State Change"
initial_state: true
trigger:
  - platform: state
    entity_id: lock.front_door
    from: "on"
    to: "off"
  - platform: state
    entity_id: lock.front_door
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "Front Door Lock state changed to '{{ states.lock.front_door.state }}'"
