alias: "Birthday: Person 1: Tomorrow"
initial_state: true
trigger:
  - platform: time
    at: "09:00:00"
  - platform: homeassistant # todo remove this test
    event: start
condition:
  - condition: state
    entity_id: input_boolean.automation_milestones
    state: "on"
  - condition: template
    value_template: "{{ (states.input_datetime.birthday_person_1.state.split('-')[1:] == ((as_timestamp(now()) + 86400) | timestamp_custom('%m-%d')).split('-')) }}"
action:
  - service: notify.ios_parents
    data:
      title: "Birthday: {{ states.input_datetime.birthday_person_1.attributes.friendly_name }}: Tomorrow"
      message: "{{ states.input_datetime.birthday_person_1.attributes.friendly_name }}'s birthday is tomorrow! TEST"
  - service: notify.slack_standard
    data:
      message: "{{ states.input_datetime.birthday_person_1.attributes.friendly_name }}'s birthday is tomorrow! TEST"
