homeassistant:
  name: VierHome
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 500
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize_domain: !include_dir_named customize_domain/
  customize: !include_dir_merge_named customize/

frontend:

config:

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3

updater:
  include_used_components: true

discovery:
  ignore:
    - songpal
    - yamaha

history:

logbook:

map:

sun:

cloud:
  alexa:
    filter:
      include_entities:
        - group.arlo # Until we're ready to actually give Alexa something

group: !include_dir_named groups/
automation: !include automations.yaml
script: !include scripts.yaml

ios:

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

device_tracker:
  - platform: bluetooth_tracker
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    ssid_filter: !secret unifi_ssid_filter

sensor: !include_dir_list configurations/sensor/

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: arlo
    home_mode_name: Sleep
  - platform: ifttt
    name: scout_alarm
    code: !secret scout_alarm_code
    event_arm_away: scout_alarm_away_armed
    event_arm_home: scout_alarm_home_armed
    event_arm_night: scout_alarm_sleep_armed
    event_disarm: scout_alarm_disarm

august:
  login_method: !secret august_login_method
  username: !secret august_username
  password: !secret august_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

media_player: !include_dir_list configurations/media_player/

history_graph: !include_dir_named configurations/history_graph/

vacuum:
  - platform: roomba
    host: !secret roomba_host
    username: !secret roomba_username
    password: !secret roomba_password
    continuous: false

ifttt:
  key: !secret ifttt_api_key

#usps:
#  username: !secret usps_username
#  password: !secret usps_password
#  driver: phantomjs

system_log:
  max_entries: 50

remote:
  - platform: harmony
    name: Family Room
    host: !secret harmony_hub_family_room_host
  - platform: harmony
    name: Loft
    host: !secret harmony_hub_loft_host

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key

climate:
  - platform: zwave
