---

# homeassistant: !include configurations/homeassistant.yaml
config:
frontend: !include frontend/frontend.yaml
history:
http: !include configurations/http.yaml
logbook:
# map:
system_log: !include configurations/system_log.yaml
# updater: !include configurations/updater.yaml

automation: !include automations.yaml
# group: !include_dir_named groups/
scene: !include scenes.yaml
script: !include scripts.yaml

# shell_command: !include services/shell_command.yaml

# alarm_control_panel: !include_dir_list configurations/alarm_control_panel/
alert: !include_dir_named configurations/alert/
# arlo: !include configurations/arlo.yaml
# august: !include configurations/august.yaml
# binary_sensor: !include_dir_list configurations/binary_sensor/
# camera: !include_dir_list configurations/camera/
# climate: !include_dir_list configurations/climate/
# cloud: !include configurations/cloud.yaml
# counter: !include_dir_named configurations/counter/
# cover: !include_dir_list configurations/cover/
# device_tracker: !include_dir_list configurations/device_tracker/
# discovery: !include configurations/discovery.yaml
ffmpeg: !include configurations/ffmpeg.yaml
# group: !include_dir_named configurations/group/
# history_graph: !include_dir_named configurations/history_graph/
# ifttt: !include configurations/ifttt.yaml
# input_boolean: !include_dir_named configurations/input_boolean/
# input_datetime: !include_dir_named configurations/input_datetime/
# ios: !include configurations/ios.yaml
# media_player: !include_dir_list configurations/media_player/
mobile_app:
# nest: !include configurations/nest.yaml
# nexia: !include configurations/nexia.yaml
notify: !include_dir_list configurations/notify/
# person: !include_dir_list configurations/person/
# pi_hole: !include configurations/pi_hole.yaml
prometheus: !include configurations/prometheus.yaml
recorder: !include configurations/recorder.yaml
# remote: !include_dir_list configurations/remote/
# roomba: !include configurations/roomba.yaml
sensor: !include_dir_list configurations/sensor/
# sun:
system_health:
# synology_dsm: !include configurations/synology_dsm.yaml
# tplink: !include configurations/tplink.yaml
# usps: !include configurations/usps.yaml
# unifi: !include configurations/unifi.yaml
# vacuum: !include_dir_list configurations/vacuum/
# weblink: !include configurations/weblink.yaml
# zone: !include_dir_list configurations/zone/
# zwave: !include configurations/zwave.yaml
