homeassistant:
  name: VierHome
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 500
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize_glob: !include customize_glob.yaml
  customize: !include_dir_merge_named customize/

frontend:

config:

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3

updater:
  include_used_components: true

discovery:
  ignore:
    - songpal
    - yamaha

history:

logbook:

map:

sun:

cloud:
  alexa:
    filter:
      include_entities:
        - group.arlo # Until we're ready to actually give Alexa something

group: !include_dir_named groups/
automation: !include automations.yaml
script: !include scripts.yaml

ios:

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

device_tracker:
  - platform: bluetooth_tracker
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    ssid_filter: !secret unifi_ssid_filter

sensor:
  - platform: moon
  - platform: api_streams
  - platform: arlo
    monitored_conditions:
      - captured_today
      - last_capture
      - total_cameras
      - battery_level
      - signal_strength
  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - alerts
      - observation_time
      - weather_1d
      - weather_1n
      - dewpoint_f
      - feelslike_f
      - heat_index_f
      - relative_humidity
      - precip_1d
      - precip_1d_in
      - precip_today_in
      - pressure_mb
      - pressure_trend
      - solarradiation
      - temp_f
      - temp_low_1d_f
      - temp_high_1d_f
      - visibility_mi
      - wind_dir
      - wind_gust_mph
      - wind_gust_1d_mph
      - wind_mph
      - wind_1d_mph
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
  - platform: time_date
    display_options:
      - date_time
  - platform: synologydsm
    host: !secret synology_host
    username: !secret synology_username
    password: !secret synology_password
    monitored_conditions:
      - cpu_total_load
      - cpu_15min_load
      - memory_real_usage
      - memory_cached
      - memory_total_swap
      - network_up
      - network_down
      - disk_smart_status
      - disk_status
      - disk_temp
      - volume_status
      - volume_percentage_used
      - volume_size_total
  - platform: haveibeenpwned
    email: !secret haveibeenpwned_email_addresses
  - platform: season
    type: astronomical
  - platform: uptime
    name: Home Assistant Uptime
  - platform: version
    name: Home Assistant Version
  - platform: steam_online
    api_key: !secret steam_api_key
    accounts: !secret steam_accounts
  - platform: ups
    username: !secret ups_username
    password: !secret ups_password
#  - platform: fedex
#    username: !secret fedex_username
#    password: !secret fedex_password
  - platform: template
    sensors:
      harmony_hub_family_room:
        value_template: '{{ states.remote.family_room.attributes.current_activity }}'
      harmony_hub_loft:
        value_template: '{{ states.remote.loft.attributes.current_activity }}'
      attic_bedroom_nest_protect_battery_status:
        value_template: "{{ states('sensor.attic_bedroom_nest_protect_battery_health') }}"
        icon_template: >-
          {% if is_state('sensor.attic_bedroom_nest_protect_battery_health', 'Ok') %}
            mdi:battery-charging-wireless
          {% else %}
            mdi:battery-charging-wireless-alert
          {% endif %}
      entryway_nest_protect_battery_status:
        value_template: "{{ states('sensor.entryway_nest_protect_battery_health') }}"
        icon_template: >-
          {% if is_state('sensor.entryway_nest_protect_battery_health', 'Ok') %}
            mdi:battery-charging-wireless
          {% else %}
            mdi:battery-charging-wireless-alert
          {% endif %}
      family_room_nest_protect_battery_status:
        value_template: "{{ states('sensor.family_room_nest_protect_battery_health') }}"
        icon_template: >-
          {% if is_state('sensor.family_room_nest_protect_battery_health', 'Ok') %}
            mdi:battery-charging-wireless
          {% else %}
            mdi:battery-charging-wireless-alert
          {% endif %}
      felicitys_bedroom_nest_protect_battery_status:
        value_template: "{{ states('sensor.felicitys_bedroom_nest_protect_battery_health') }}"
        icon_template: >-
          {% if is_state('sensor.felicitys_bedroom_nest_protect_battery_health', 'Ok') %}
            mdi:battery-charging-wireless
          {% else %}
            mdi:battery-charging-wireless-alert
          {% endif %}
      master_bedroom_nest_protect_battery_status:
        value_template: "{{ states('sensor.master_bedroom_nest_protect_battery_health') }}"
        icon_template: >-
          {% if is_state('sensor.master_bedroom_nest_protect_battery_health', 'Ok') %}
            mdi:battery-charging-wireless
          {% else %}
            mdi:battery-charging-wireless-alert
          {% endif %}
      upstairs_nest_protect_battery_status:
        value_template: "{{ states('sensor.attic_bedroom_nest_protect_battery_health') }}"
        icon_template: >-
          {% if is_state('sensor.attic_bedroom_nest_protect_battery_health', 'Ok') %}
            mdi:battery-charging-wireless
          {% else %}
            mdi:battery-charging-wireless-alert
          {% endif %}
      season_display:
        value_template: "{{ states('sensor.season') }}"
        icon_template: >-
          {% if is_state('sensor.season', 'winter') %}
            mdi:snow
          {% elif is_state('sensor.season', 'spring') %}
            mdi:flower
          {% elif is_state('sensor.season', 'summer') %}
            mdi:weather-sunny
          {% else %}
            mdi:leaf
          {% endif %}
      attic_bedroom_nest_protect_online:
        value_template: "{{ states('binary_sensor.attic_bedroom_nest_protect_online') }}"
        icon_template: >-
          {% if is_state('binary_sensor.attic_bedroom_nest_protect_online', 'on') %}
            mdi:wifi
          {% else %}
            mdi:wifi-off
          {% endif %}
      entryway_nest_protect_online:
        value_template: "{{ states('binary_sensor.entryway_nest_protect_online') }}"
        icon_template: >-
          {% if is_state('binary_sensor.entryway_nest_protect_online', 'on') %}
            mdi:wifi
          {% else %}
            mdi:wifi-off
          {% endif %}
      family_room_nest_protect_online:
        value_template: "{{ states('binary_sensor.family_room_nest_protect_online') }}"
        icon_template: >-
          {% if is_state('binary_sensor.family_room_nest_protect_online', 'on') %}
            mdi:wifi
          {% else %}
            mdi:wifi-off
          {% endif %}
      felicitys_bedroom_nest_protect_online:
        value_template: "{{ states('binary_sensor.felicitys_bedroom_nest_protect_online') }}"
        icon_template: >-
          {% if is_state('binary_sensor.felicitys_bedroom_nest_protect_online', 'on') %}
            mdi:wifi
          {% else %}
            mdi:wifi-off
          {% endif %}
      master_bedroom_nest_protect_online:
        value_template: "{{ states('binary_sensor.master_bedroom_nest_protect_online') }}"
        icon_template: >-
          {% if is_state('binary_sensor.master_bedroom_nest_protect_online', 'on') %}
            mdi:wifi
          {% else %}
            mdi:wifi-off
          {% endif %}
      upstairs_nest_protect_online:
        value_template: "{{ states('binary_sensor.upstairs_nest_protect_online') }}"
        icon_template: >-
          {% if is_state('binary_sensor.upstairs_nest_protect_online', 'on') %}
            mdi:wifi
          {% else %}
            mdi:wifi-off
          {% endif %}
  - platform: crimereports
    name: Crime
    radius: 3000

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: arlo
    home_mode_name: Sleep
  - platform: ifttt
    name: scout_alarm
    code: !secret scout_alarm_code
    event_arm_away: scout_alarm_away_armed
    event_arm_home: scout_alarm_home_armed
    event_arm_night: scout_alarm_sleep_armed
    event_disarm: scout_alarm_disarm

august:
  login_method: !secret august_login_method
  username: !secret august_username
  password: !secret august_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

media_player:
  - platform: cast
  - platform: yamaha
    host: !secret yamaha_host
  - platform: braviatv
    host: !secret bravia_host
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

history_graph:
  gr1:
    name: Security
    hours_to_show: 24
    refresh: 300
    entities:
      - lock.front_door
      - cover.viergarage
      - alarm_control_panel.scout_alarm
      - alarm_control_panel.vierarlo
  gr2:
    name: Lights
    hours_to_show: 24
    refresh: 300
    entities:
      - light.family_room
      - light.felicitys_bedroom
      - light.loft
      - light.master_bedroom
  gr3:
    name: Family Presence
    hours_to_show: 24
    refresh: 300
    entities:
      - device_tracker.zonephone
      - device_tracker.mermaidphone
      - device_tracker.vierhapad
  gr4:
    name: Steam Presence
    hours_to_show: 24
    refresh: 300
    entities: !secret steam_presence_group_entities

vacuum:
  - platform: roomba
    host: !secret roomba_host
    username: !secret roomba_username
    password: !secret roomba_password
    continuous: false

ifttt:
  key: !secret ifttt_api_key

#usps:
#  username: !secret usps_username
#  password: !secret usps_password
#  driver: phantomjs

system_log:
  max_entries: 50

remote:
  - platform: harmony
    name: Family Room
    host: !secret harmony_hub_family_room_host
  - platform: harmony
    name: Loft
    host: !secret harmony_hub_loft_host

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key

climate:
  - platform: zwave
