homeassistant: !include configurations/homeassistant.yaml
config:
frontend:
history:
http: !include configurations/http.yaml
logbook:
map:
system_log: !include configurations/system_log.yaml
updater: !include configurations/updater.yaml

automation: !include_dir_list automations/
group: !include_dir_named groups/
script: !include_dir_merge_named scripts/

shell_command: !include services/shell_command.yaml

alarm_control_panel: !include_dir_list configurations/alarm_control_panel/
alert: !include_dir_named configurations/alert/
arlo: !include configurations/arlo.yaml
august: !include configurations/august.yaml
binary_sensor: !include_dir_list configurations/binary_sensor/
camera: !include_dir_list configurations/camera/
climate: !include_dir_list configurations/climate/
cloud: !include configurations/cloud.yaml
cover: !include_dir_list configurations/cover/
device_tracker: !include_dir_list configurations/device_tracker/
discovery: !include configurations/discovery.yaml
ffmpeg: !include configurations/ffmpeg.yaml
history_graph: !include_dir_named configurations/history_graph/
ifttt: !include configurations/ifttt.yaml
input_boolean: !include_dir_named configurations/input_boolean/
ios: !include configurations/ios.yaml
media_player: !include_dir_list configurations/media_player/
nest: !include configurations/nest.yaml
notify: !include_dir_list configurations/notify/
remote: !include_dir_list configurations/remote/
sensor: !include_dir_list configurations/sensor/
sun:
#usps: !include configurations/usps.yaml
vacuum: !include_dir_list configurations/vacuum/
weblink: !include configurations/weblink.yaml
zone: !include_dir_list configurations/zone/
zwave: !include configurations/zwave.yaml
