alias: "Chore: Download Sensitive Documents: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "10:00:00"
  - platform: time
    at: "12:00:00"
  - platform: time
    at: "14:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: template
    value_template: "{{ (states.input_boolean.chore_download_sensitive_documents.state == 'on') }}"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_download_sensitive_documents
  - service: persistent_notification.create
    data:
      title: "Chore: Download Sensitive Documents"
      message: "Download all of the family's sensitive documents to encrypted drives"
      notification_id: chore_download_sensitive_documents
  - service: notify.ios_parents
    data_template:
      title: "Chore: Download Sensitive Documents"
      message: "Download all of the family's sensitive documents to encrypted drives"
      data:
        push:
          category: chore
        action_data:
          entity_id: input_boolean.chore_download_sensitive_documents
