alias: "Chore: Download Sensitive Documents: Reset"
initial_state: true
trigger:
  - platform: time
    at: "08:00:00"
condition:
  - condition: template
    value_template: "{{ (now().day == 1) }}" # First day of month
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_download_sensitive_documents
