alias: "Alarms: Arlo: Combined Alarm Disarmed"
trigger:
  - platform: state
    entity_id: alarm_control_panel.combined_alarm
    to: disarmed
condition:
  - condition: state
    entity_id: input_boolean.automation_combined_alarm
    state: on
  - condition: template
    value_template: "{{ (states.alarm_control_panel.vierarlo.state != 'disarmed') }}"
action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.vierarlo
