---

alias: "Notification: Home Assistant: Shutdown"
initial_state: true
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: notify.slack
    target: "#home-assistant"
    data:
      message: Home Assistant shutting down
