---

alias: "Notification: Home Assistant: Start"
initial_state: true
trigger:
  - platform: homeassistant
    event: start
action:
  - service: notify.slack
    target: "#home-assistant"
    data:
      message: Home Assistant starting up
