---

alias: "Chore: Cycle Litter Boxes: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "17:00:00"
  - platform: time
    at: "18:00:00"
  - platform: time
    at: "19:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_cycle_litter_boxes
    state: "on"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_cycle_litter_boxes
  - service: persistent_notification.create
    data:
      title: "Chore: Cycle Litter Boxes"
      message: Empty the litter boxes and fill with fresh litter
      notification_id: chore_cycle_litter_boxes
  - service: notify.mobile_app_parents
    data_template:
      title: "Chore: Cycle Litter Boxes"
      message: Empty the litter boxes and fill with fresh litter
      data:
        push:
          category: chore
        action_data:
          entity_id: input_boolean.chore_cycle_litter_boxes
