alias: "Chore: Update Budget: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "10:00:00"
  - platform: time
    at: "12:00:00"
  - platform: time
    at: "14:00:00"
  - platform: time
    at: "16:00:00"
  - platform: time
    at: "18:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_update_budget
    state: "on"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_update_budget
  - service: persistent_notification.create
    data:
      title: "Chore: Update Budget"
      message: Update the budget in YNAB for next month
      notification_id: chore_update_budget
  - service: notify.mobile_app_parents
    data_template:
      title: "Chore: Update Budget"
      message: Update the budget in YNAB for next month
      data:
        push:
          category: chore
        action_data:
          entity_id: input_boolean.chore_update_budget
