---

alias: "Birthday: Person 19: In 2 Days"
initial_state: true
trigger:
  - platform: time
    at: "09:00:00"
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.automation_milestones
    state: "on"
  - condition: template
    value_template: "{{ (states('input_datetime.birthday_person_19').split('-')[1:] == ((as_timestamp(now()) + 172800) | timestamp_custom('%m-%d')).split('-')) }}"
action:
  - service: notify.mobile_app_parents
    data:
      title: "Birthday: {{ state_attr('input_datetime.birthday_person_19', 'friendly_name') }}: In 2 Days"
      message: "{{ state_attr('input_datetime.birthday_person_19', 'friendly_name') }}'s birthday is in 2 days!"
  - service: notify.slack_standard
    data:
      message: "{{ state_attr('input_datetime.birthday_person_19', 'friendly_name') }}'s birthday is in 2 days!"
