alias: "Notification: Nest Protect: Smoke Status Change: Attic Bedroom"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.attic_bedroom_nest_protect_smoke_status
action:
  - service: notify.slack
    data:
      message: "Attic Bedroom Nest Protect smoke status changed to '{{ states.sensor.attic_bedroom_nest_protect_smoke_status.state }}'"
      target:
        - "#fox-hollow-ha"
        - "#fox-hollow-ha-crit"
