alias: "Notification: Nest Protect: Smoke Status Change: Family Room"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.family_room_nest_protect_smoke_status
condition:
  - condition: state
    entity_id: binary_sensor.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "Family Room Nest Protect smoke status changed to '{{ states.sensor.family_room_nest_protect_smoke_status.state }}'"
