alias: "Notification: Nest Protect: Master Bedroom: Smoke Status Change"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.nest_protect_master_bedroom_smoke_status
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "Nest Protect: Master Bedroom: Smoke status changed to '{{ states('sensor.nest_protect_master_bedroom_smoke_status') }}'"
