alias: "Notification: Nest Protect: Smoke Status Change: Master Bedroom"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.master_bedroom_nest_protect_smoke_status
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "Master Bedroom Nest Protect smoke status changed to '{{ states.sensor.master_bedroom_nest_protect_smoke_status.state }}'"
