alias: "Notification: Nest Protect: Upstairs: Smoke Status Change"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.nest_protect_upstairs_smoke_status
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: on
action:
  - service: notify.slack_crit
    data:
      message: "Nest Protect: Upstairs: Smoke status changed to '{{ states.sensor.nest_protect_upstairs_smoke_status.state }}'"
