alias: "Notification: Nest Protect: Smoke Status Change: Upstairs"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.upstairs_nest_protect_smoke_status
action:
  - service: notify.slack
    data:
      message: "Upstairs Nest Protect smoke status changed to '{{ states.sensor.upstairs_nest_protect_smoke_status.state }}'"
      target:
        - '#fox-hollow-ha'
        - '#fox-hollow-ha-crit'
