- alias: "Notification: Email Breaches Change: Cait's Film"
  initial_state: true
  trigger:
    - platform: state
      entity_id: !secret breaches_caits_film_email
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.from_state.state != 'unknown' }}"
      - condition: template
        value_template: "{{ trigger.to_state.state != 'unknown' }}"
  action:
    - service: notify.slack
      data:
        message: !secret automation_breaches_caits_film_email_notification_message
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
