alias: "Notification: Email Breaches Change: Family"
initial_state: true
trigger:
  - platform: state
    entity_id: !secret breaches_family_email
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ trigger.from_state.state != 'unknown' }}"
    - condition: template
      value_template: "{{ trigger.to_state.state != 'unknown' }}"
action:
  - service: notify.slack_crit
    data:
      message: !secret automation_breaches_family_email_notification_message
