alias: "Notification: Email Breaches Change: Felicity's Personal"
initial_state: true
trigger:
  - platform: state
    entity_id: !secret breaches_felicitys_email
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
  - condition: template
    value_template: "{{ (trigger.from_state.state != 'unknown') }}"
  - condition: template
    value_template: "{{ (trigger.to_state.state != 'unknown') }}"
action:
  - service: notify.slack_crit
    data:
      message: !secret automation_breaches_felicitys_email_notification_message
