---

alias: "Alarms: Combined Alarm: Arlo Triggered"
trigger:
  - platform: state
    entity_id: alarm_control_panel.vierarlo
    to: triggered
condition:
  - condition: state
    entity_id: input_boolean.automation_combined_alarm
    state: "on"
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.combined_alarm
    data:
      code: !secret alarm_code
