alias: "Chore: Recharge Fire Extinguishers: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_recharge_fire_extinguishers
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: on
  - condition: template
    value_template: "{{ (states.input_boolean.chore_recharge_fire_extinguishers.state == 'off') }}"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_recharge_fire_extinguishers
  - service: notify.ios_parents
    data:
      title: "Chore: Recharge Fire Extinguishers"
      message: "The fire extinguishers have been recharged (let's never need them)"
  - service: notify.slack_standard
    data:
      message: "The chore 'Recharge Fire Extinguishers' has been completed"
