alias: "Chore: Recharge Fire Extinguishers: Reset"
initial_state: true
trigger:
  - platform: time
    at: "08:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: template
    value_template: "{{ (now().month == 5) }}" # May
  - condition: template
    value_template: "{{ (now().day == 1) }}" # 1st day of month
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_recharge_fire_extinguishers
  - service: notify.slack_standard
    data:
      message: "The chore 'Recharge Fire Extinguishers' is due today"
