alias: "Chore: Clean Dyson Vacuum Filters: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "12:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_clean_dyson_vacuum_filters
    state: "on"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_clean_dyson_vacuum_filters
  - service: persistent_notification.create
    data:
      title: "Chore: Clean Dyson Vacuum Filters"
      message: "Clean the Dyson vacuum cleaner's filters"
      notification_id: chore_clean_dyson_vacuum_filters
  - service: notify.ios_parents
    data_template:
      title: "Chore: Clean Dyson Vacuum Filters"
      message: "Clean the Dyson vacuum cleaner's filters"
      data:
        push:
          category: chore
        action_data:
          entity_id: input_boolean.chore_clean_dyson_vacuum_filters
