---

alias: "Chore: Take Bins To Curb: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_take_bins_to_curb
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_take_bins_to_curb
    state: "off"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_take_bins_to_curb
  - service: notify.mobile_app_parents
    data:
      title: "Chore: Take Bins To Curb"
      message: The bins have been taken to the curb
  - service: notify.slack_standard
    data:
      message: "The chore 'Take Bins To Curb' has been completed"
