alias: "Chore: Clean Dyson Vacuum Filters: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_clean_dyson_vacuum_filters
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_clean_dyson_vacuum_filters
    state: "off"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_clean_dyson_vacuum_filters
  - service: notify.ios_parents
    data:
      title: "Chore: Clean Dyson Vacuum Filters"
      message: "The Dyson vacuum's filters have been cleaned"
  - service: notify.slack_standard
    data:
      message: "The chore 'Clean Dyson Vacuum Filters' has been completed"
