alias: "Anniversary: Event 1: In 4 Weeks"
initial_state: true
trigger:
  - platform: time
    at: "09:00:00"
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.automation_milestones
    state: "on"
  - condition: template
    value_template: "{{ (states.input_datetime.anniversary_1.state.split('-')[1:] == ((as_timestamp(now()) + 2419200) | timestamp_custom('%m-%d')).split('-')) }}"
action:
  - service: notify.ios_parents
    data:
      title: "Anniversary: {{ states.input_datetime.anniversary_1.attributes.friendly_name }}: In 4 Weeks"
      message: "{{ states.input_datetime.anniversary_1.attributes.friendly_name }} anniversary is in 4 weeks!"
  - service: notify.slack_standard
    data:
      message: "{{ states.input_datetime.anniversary_1.attributes.friendly_name }} anniversary is in 4 weeks!"
