alias: "Chore: Replace Toothbrush Heads: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "12:00:00"
condition:
  - condition: template
    value_template: "{{ (states.input_boolean.chore_replace_toothbrush_heads.state == 'on') }}"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_replace_toothbrush_heads
  - service: persistent_notification.create
    data:
      title: "Chore: Replace Toothbrush Heads"
      message: "Replace the parents' electric toothbrush heads"
      notification_id: chore_replace_toothbrush_heads
  - service: notify.ios_parents
    data_template:
      title: "Chore: Replace Toothbrush Heads"
      message: "Replace the parents' electric toothbrush heads"
      data:
        push:
          category: chore
        action_data:
          entity_id: input_boolean.chore_replace_toothbrush_heads
