alias: "Alarms: Combined Alarm: Other Armed Away"
trigger:
#  - platform: state
#    entity_id: alarm_control_panel.vierarlo
#    to: armed_away
  - platform: state
    entity_id: alarm_control_panel.scout_alarm
    to: armed_away
condition:
  - condition: state
    entity_id: input_boolean.automation_combined_alarm
    state: "on"
action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.combined_alarm
    data:
      code: !secret alarm_code
