alias: "Alarms: Combined Alarm: Self Armed Away"
trigger:
  - platform: state
    entity_id: alarm_control_panel.combined_alarm
    to: armed_away
condition:
  - condition: state
    entity_id: input_boolean.automation_combined_alarm
    state: "on"
action:
  - delay:
      minutes: 5
  - service: cover.close_cover
    entity_id: cover.garage_door
  - service: lock.lock
    entity_id: lock.front_door
  - service: light.turn_off
    entity_id:
      - light.attic_bedroom_ceiling
      - light.family_room_ceiling
      - light.master_bedroom_ceiling
      - light.nursery_ceiling
      - light.nursery_lamp
  - service: switch.turn_off
    entity_id:
      - switch.caits_desk_lamp
      - switch.front_room_east_lamp
      - switch.front_room_west_lamp
      - switch.loft_lamp
      - switch.master_bedroom_humidifier
      - switch.roberts_reading_lamp
