alias: "Notification: Steam Presence Change: Cait"
initial_state: true
trigger:
  - platform: state
    entity_id: !secret steam_presence_cait
action:
  - service: notify.slack_standard
    data:
      message: !secret automation_steam_presence_cait_notification_message
