alias: "Notification: Steam Presence Change: Robert"
initial_state: true
trigger:
  - platform: state
    entity_id: !secret steam_presence_robert
condition:
  - condition: state
    entity_id: binary_sensor.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_standard
    data:
      message: !secret automation_steam_presence_robert_notification_message
