alias: "Chore: Sort Synced Photos On NAS: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "12:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: on
  - condition: state
    entity_id: input_boolean.chore_sort_synced_photos_on_nas
    state: on
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_sort_synced_photos_on_nas
  - service: persistent_notification.create
    data:
      title: "Chore: Sort Synced Photos On NAS"
      message: Sort the synced photos on the NAS into good folders
      notification_id: chore_sort_synced_photos_on_nas
  - service: notify.mobile_app_parents
    data_template:
      title: "Chore: Sort Synced Photos On NAS"
      message: Sort the synced photos on the NAS into good folders
      data:
        push:
          category: chore
        action_data:
          entity_id: input_boolean.chore_sort_synced_photos_on_nas
