---

alias: "Notification: Crime Change"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.crime
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "Crime changed to '{{ states('sensor.crime') }}'"
  - service: notify.smtp_parents
    data:
      title: Crime Change
      message: "Crime changed to '{{ states('sensor.crime') }}'"
