alias: "Themes: Day: Startup"
initial_state: true
trigger:
  - platform: homeassistant
    event: start
condition:
  - condition: sun
    before: sunrise
    before_offset: "+00:30:00"
  - condition: state
    entity_id: input_boolean.automation_times
    state: "on"
action:
  - service: frontend.set_theme
    data:
      name: default