alias: "Themes: Day: Startup"
initial_state: true
trigger:
  - platform: homeassistant
    event: start
condition:
  - condition: sun
    after: sunrise
    before: sunset
  - condition: state
    entity_id: input_boolean.automation_times
    state: on
action:
  - service: frontend.set_theme
    data:
      name: default
