alias: "Themes: Night: Startup"
initial_state: true
trigger:
  - platform: homeassistant
    event: start
condition:
  - condition: sun
    after: sunset
    before: sunrise
  - condition: state
    entity_id: input_boolean.automation_times
    state: "on"
action:
  - service: frontend.set_theme
    data:
      name: dark_cyan
