alias: "Alarms: Arlo: Combined Alarm Triggered"
trigger:
  - platform: state
    entity_id: alarm_control_panel.combined_alarm
    to: triggered
condition:
  - condition: state
    entity_id: input_boolean.automation_combined_alarm
    state: on
action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.vierarlo
