alias: "Alarms: Combined Alarm: Other Armed Home"
trigger:
  - platform: state
    entity_id: alarm_control_panel.vierarlo
    to: armed_home
  - platform: state
    entity_id: alarm_control_panel.scout_alarm
    to: armed_home
condition:
  - condition: template
    value_template: "{{ (states.alarm_control_panel.combined_alarm.state != 'armed_home') }}"
action:
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.combined_alarm
