- alias: "Cait's Film Email Breaches Change"
  initial_state: true
  trigger:
    - platform: state
      entity_id: !secret breaches_caits_film_email
  action:
    - service: notify.slack
      data:
        message: !secret automation_breaches_caits_film_email_notification_message
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
