- alias: Family Email Breaches Change
  initial_state: true
  trigger:
    - platform: state
      entity_id: !secret breaches_family_email
  action:
    - service: notify.slack
      data:
        message: !secret automation_breaches_family_email_notification_message
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
