- alias: "Robert's Email Breaches Change"
  initial_state: true
  trigger:
    - platform: state
      entity_id: !secret breaches_roberts_email
  action:
    - service: notify.slack
      data:
        message: !secret automation_breaches_roberts_email_notification_message
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
