- alias: "Notification: Chamberlain Garage Door State Change"
  initial_state: true
  trigger:
    - platform: state
      entity_id: cover.viergarage
  action:
    - service: notify.slack
      data:
        message: "Chamberlain Garage Door state changed to '{{ states.cover.viergarage.state }}'"
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
