alias: "Notification: Chamberlain Garage Door State Change"
initial_state: true
trigger:
  - platform: state
    entity_id: cover.viergarage
condition:
  - condition: state
    entity_id: binary_sensor.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "Chamberlain Garage Door state changed to '{{ states.cover.viergarage.state }}'"
