alias: "Notification: Chamberlain Garage Door State Change"
initial_state: true
trigger:
  - platform: state
    entity_id: cover.viergarage
action:
  - service: notify.slack_crit
    data:
      message: "Chamberlain Garage Door state changed to '{{ states.cover.viergarage.state }}'"
