alias: "Notification: Crime Change"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.crime
condition:
  - condition: state
    entity_id: binary_sensor.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "Crime changed to '{{ states.sensor.crime.state }}'"
