alias: "Notification: Garage Door: State Change"
initial_state: true
trigger:
  - platform: state
    entity_id: cover.garage_door
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "Garage Door state changed to '{{ states('cover.garage_door') }}'"
