- alias: Nursery Nest Protect Smoke Status Change
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.nursery_nest_protect_smoke_status
  action:
    - service: notify.slack
      data:
        message: "Nursery Nest Protect smoke status changed to '{{ states.sensor.nursery_nest_protect_smoke_status.state }}'"
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
