- alias: Family Room Nest Protect Battery Health Change
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.family_room_nest_protect_battery_health
  action:
    - service: notify.slack
      data:
        message: "Family Room Nest Protect battery health changed to '{{ states.sensor.family_room_nest_protect_battery_health.state }}'"
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
