- alias: "Felicity's Bedroom Nest Protect Battery Health Change"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.felicitys_bedroom_nest_protect_battery_health
  action:
    - service: notify.slack
      data:
        message: "Felicity's Bedroom Nest Protect battery health changed to '{{ states.sensor.felicitys_bedroom_nest_protect_battery_health.state }}'"
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
