- alias: Master Bedroom Nest Protect Smoke Status Change
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.master_bedroom_nest_protect_smoke_status
  action:
    - service: notify.slack
      data:
        message: "Master Bedroom Nest Protect smoke status changed to '{{ states.sensor.master_bedroom_nest_protect_smoke_status.state }}'"
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
