- alias: "Felicity's Bedroom Nest Protect Carbon Monoxide Status Change"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.felicitys_bedroom_nest_protect_co_status
  action:
    - service: notify.slack
      data:
        message: "Felicity's Bedroom Nest Protect carbon monoxide status changed to '{{ states.sensor.felicitys_bedroom_nest_protect_co_status.state }}'"
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
