alias: "Notification: Scout Alarm Mode Change"
initial_state: true
trigger:
  - platform: state
    entity_id: alarm_control_panel.scout_alarm
action:
  - service: notify.slack
    data:
      message: "Scout Alarm mode changed to '{{ states.alarm_control_panel.scout_alarm.state }}'"
      target:
        - '#fox-hollow-ha'
        - '#fox-hollow-ha-crit'
