alias: "Notification: UPS Packages Change"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.ups
action:
  - service: notify.slack_standard
    data:
      message: >
        UPS has {{ states.sensor.ups.state }} package{% if states.sensor.ups.state > 1 %}s{% endif %}
        to deliver today
