alias: "Chore: Clean Backyard: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_clean_backyard
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_clean_backyard
    state: "off"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_clean_backyard
  - service: notify.ios_parents
    data:
      title: "Chore: Clean Backyard"
      message: "The backyard has been cleaned"
  - service: notify.slack_standard
    data:
      message: "The chore 'Clean Backyard' has been completed"
