alias: "Chore: Clean Backyard: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "12:00:00"
  - platform: time
    at: "14:00:00"
  - platform: time
    at: "16:00:00"
  - platform: time
    at: "18:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: template
    value_template: "{{ (states.input_boolean.chore_clean_backyard.state == 'on') }}"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_clean_backyard
  - service: persistent_notification.create
    data:
      title: "Chore: Clean Backyard"
      message: "Clean the backyard of debris and poo"
      notification_id: chore_clean_backyard
  - service: notify.ios_parents
    data_template:
      title: "Chore: Clean Backyard"
      message: "Clean the backyard of debris and poo"
      data:
        push:
          category: chore
        action_data:
          entity_id: input_boolean.chore_clean_backyard
