alias: "Chore: Clean Backyard: Reset"
initial_state: true
trigger:
  - platform: time
    at: "08:00:00"
condition:
  - condition: state
    entity_id: binary_sensor.automation_chores
    state: "on"
  - condition: template
    value_template: "{{ (now().isoweekday() == 6) }}" # Saturday
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_clean_backyard
  - service: notify.slack_standard
    data:
      message: "The chore 'Clean Backyard' is due today"
