alias: "Chore: Clean Coffee Grinder: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_clean_coffee_grinder
condition:
  - condition: template
    value_template: "{{ (states.input_boolean.chore_clean_coffee_grinder.state == 'off') }}"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_clean_coffee_grinder
  - service: notify.ios_parents
    data:
      title: "Chore: Clean Coffee Grinder"
      message: "The coffee grinder has been cleaned"
