alias: "Notification: Steam Game Change: Robert"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.steam_game_playing_robert
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
  - condition: template
    value_template: "{{ (trigger.from_state.state != 'unknown') }}"
  - condition: template
    value_template: "{{ (trigger.to_state.state != 'unknown') }}"
action:
  - service: notify.slack_standard
    data:
      message: "Robert's Steam game changed to '{{ states('sensor.steam_game_playing_robert') }}'"
