alias: "Notification: Home Assistant: Shutdown"
initial_state: true
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: notify.slack_standard
    data:
      message: "Home Assistant shutting down"
