alias: "Notification: Home Assistant: Shutdown"
initial_state: true
trigger:
  - platform: homeassistant
    event: shutdown
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_standard
    data:
      message: Home Assistant shutting down
