---

alias: "Chore: Have Gutters Cleaned: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_have_gutters_cleaned
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_have_gutters_cleaned
    state: "off"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_have_gutters_cleaned
  - service: notify.mobile_app_parents
    data:
      title: "Chore: Have Gutters Cleaned"
      message: "The gutters have been cleaned, so let's enjoy a lack of backyard puddles"
  - service: notify.slack_standard
    data:
      message: "The chore 'Have Gutters Cleaned' has been completed"
