alias: "Chore: Clean Coffee Grinder: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_clean_coffee_grinder
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_clean_coffee_grinder
    state: "off"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_clean_coffee_grinder
  - service: notify.mobile_app_parents
    data:
      title: "Chore: Clean Coffee Grinder"
      message: "The coffee grinder has been cleaned"
  - service: notify.slack_standard
    data:
      message: "The chore 'Clean Coffee Grinder' has been completed"
