alias: "Notification: Presence Change: Cait"
initial_state: true
trigger:
  - platform: state
    entity_id: person.cait
    from: not_home
    to: home
  - platform: state
    entity_id: person.cait
    from: home
    to: not_home
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_standard
    data:
      message: "Cait's presence changed to '{{ states.person.cait.state }}'"
