alias: "Notification: Presence Change: Cait"
initial_state: true
trigger:
  - platform: state
    entity_id: device_tracker.mermaidphone
    from: "not_home"
    to: "home"
  - platform: state
    entity_id: device_tracker.mermaidphone
    from: "home"
    to: "not_home"
condition:
  - condition: state
    entity_id: binary_sensor.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_standard
    data:
      message: "Cait's presence changed to '{{ states.device_tracker.mermaidphone.state }}'"
