alias: "Notification: Presence Change: Olivia"
initial_state: true
trigger:
  - platform: state
    entity_id: device_tracker.lolli
    from: "not_home"
    to: "home"
  - platform: state
    entity_id: device_tracker.lolli
    from: "home"
    to: "not_home"
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_standard
    data:
      message: "Olivia's presence changed to '{{ states.device_tracker.lolli.state }}'"
