- alias: "Notification: Presence Change: Olivia"
  initial_state: true
  trigger:
    - platform: state
      entity_id: device_tracker.lolli
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.lolli
      from: 'home'
      to: 'not_home'
  action:
    - service: notify.slack
      data:
        message: "Olivia's presence changed to '{{ states.device_tracker.lolli.state }}'"
        target:
          - '#fox-hollow-ha'
