alias: "Notification: Presence Change: Robert"
initial_state: true
trigger:
  - platform: state
    entity_id: device_tracker.zonephone
    from: "not_home"
    to: "home"
  - platform: state
    entity_id: device_tracker.zonephone
    from: "home"
    to: "not_home"
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: on
action:
  - service: notify.slack_standard
    data:
      message: "Robert's presence changed to '{{ states.device_tracker.zonephone.state }}'"
