alias: "Alarms: Arlo: Combined Alarm Armed Night"
trigger:
  - platform: state
    entity_id: alarm_control_panel.combined_alarm
    to: armed_night
condition:
  - condition: state
    entity_id: input_boolean.automation_combined_alarm
    state: "on"
  - condition: template
    value_template: "{{ (states.alarm_control_panel.vierarlo.state != 'armed_night') }}"
action:
  - service: alarm_control_panel.alarm_arm_night
    entity_id: alarm_control_panel.vierarlo
