alias: "Times: Theme: Day"
trigger:
  - platform: sun
    event: sunrise
    offset: '+00:00:00'
condition:
  - condition: state
    entity_id: input_boolean.automation_times
    state: "on"
action:
  - service: frontend.set_theme
    data:
      name: default
