alias: "Notification: Alarms: Arlo: Mode Change"
initial_state: true
trigger:
  - platform: state
    entity_id: alarm_control_panel.vierarlo
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
  - condition: template
    value_template: "{{ (trigger.from_state.state != 'unknown') }}"
  - condition: template
    value_template: "{{ (trigger.to_state.state != 'unknown') }}"
action:
  - service: notify.slack_crit
    data:
      message: "Arlo mode changed to '{{ states.alarm_control_panel.vierarlo.state }}'"
