alias: "Alarms: Scout Alarm: Combined Alarm Triggered"
trigger:
  - platform: state
    entity_id: alarm_control_panel.combined_alarm
    to: triggered
condition:
  - condition: state
    entity_id: input_boolean.automation_combined_alarm
    state: "on"
  - condition: template
    value_template: "{{ (states.alarm_control_panel.scout_alarm.state != 'triggered') }}"
action:
  - service: alarm_control_panel.trigger_alarm
    entity_id: alarm_control_panel.scout_alarm
    data:
      code: !secret alarm_code
