alias: "Alarms: Scout Alarm: Combined Alarm Armed Home"
trigger:
  - platform: state
    entity_id: alarm_control_panel.combined_alarm
    to: armed_home
condition:
  - condition: state
    entity_id: input_boolean.automation_combined_alarm
    state: "on"
  - condition: template
    value_template: "{{ (states.alarm_control_panel.scout_alarm.state != 'armed_home') }}"
action:
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.scout_alarm
