alias: "Alarms: Scout Alarm: Mark Disarmed On Startup"
initial_state: true
trigger:
  - platform: homeassistant
    event: start
action:
  - delay:
      minutes: 2
  - service: shell_command.scout_alarm_mark_disarmed
  - delay:
      minutes: 1
  - service: counter.decrement
    entity_id: counter.startup_activities
