---

alias: "Chore: Update Budget: Reset"
initial_state: true
trigger:
  - platform: time
    at: "06:00:00"
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: template
    value_template: "{{ ((((as_timestamp(now()) + (24 * 60 * 60)) | timestamp_custom('%d', true)) | int) == 1) }}" # Last day of month (tomorrow is day 1)
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_update_budget
  - service: notify.slack_standard
    data:
      message: "The chore 'Update Budget' is due today"
