alias: "Alarms: Combined Alarm: Self Armed Home or Night"
trigger:
  - platform: state
    entity_id: alarm_control_panel.combined_alarm
    to: armed_home
  - platform: state
    entity_id: alarm_control_panel.combined_alarm
    to: armed_night
condition:
  - condition: state
    entity_id: input_boolean.automation_combined_alarm
    state: on
action:
  - service: cover.close_cover
    entity_id: cover.garage_door
  - service: lock.lock
    entity_id: lock.front_door
