---

alias: "Notification: Alarms: Scout Alarm: Mode Change"
initial_state: true
trigger:
  - platform: state
    entity_id: alarm_control_panel.scout_alarm
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "Scout Alarm mode changed to '{{ states('alarm_control_panel.scout_alarm') }}'"
