alias: IFTTT
trigger:
  - event_data:
      action: call_service
    event_type: ifttt_webhook_received
    platform: event
condition: []
action:
  - data_template:
      entity_id: "{{ trigger.event.data.entity_id }}"
      state: "{{ trigger.event.data.state }}"
    service_template: "{{ trigger.event.data.service }}"
