alias: "Notification: Nest Protect: Battery Health Change: Attic Bedroom"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.attic_bedroom_nest_protect_battery_health
action:
  - service: notify.slack_crit
    data:
      message: "Attic Bedroom Nest Protect battery health changed to '{{ states.sensor.attic_bedroom_nest_protect_battery_health.state }}'"
