alias: "Notification: Nest Protect: Battery Health Change: Master Bedroom"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.master_bedroom_nest_protect_battery_health
action:
  - service: notify.slack_crit
    data:
      message: "Master Bedroom Nest Protect battery health changed to '{{ states.sensor.master_bedroom_nest_protect_battery_health.state }}'"
