- alias: "Notification: Nest Protect: Battery Health Change: Nursery"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.nursery_nest_protect_battery_health
  action:
    - service: notify.slack
      data:
        message: "Nursery Nest Protect battery health changed to '{{ states.sensor.nursery_nest_protect_battery_health.state }}'"
        target:
          - '#fox-hollow-ha'
          - '#fox-hollow-ha-crit'
