alias: "Chore: Cycle Litter Boxes: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_cycle_litter_boxes
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: template
    value_template: "{{ (states.input_boolean.chore_cycle_litter_boxes.state == 'off') }}"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_cycle_litter_boxes
  - service: notify.ios_parents
    data:
      title: "Chore: Cycle Litter Boxes"
      message: "The litter boxes have been cycled with fresh litter"
  - service: notify.slack_standard
    data:
      message: "The chore 'Cycle Litter Boxes' has been completed"
