alias: "Chore: Cycle Litter Boxes: Notification Touched Done"
initial_state: true
trigger:
  platform: event
  event_type: html5_notification.clicked
  event_data:
    action: CHORE_CYCLE_LITTER_BOXES_DONE
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.chore_cycle_litter_boxes
