alias: "Chore: Cycle Litter Boxes: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "17:00:00"
  - platform: time
    at: "18:00:00"
  - platform: time
    at: "19:00:00"
condition:
  - condition: template
    value_template: "{{ states.input_boolean.chore_cycle_litter_boxes.state == 'on' }}"
action:
  - service: notify.ios_parents
    data_template:
      title: "Chore: Cycle Litter Boxes"
      message: "Empty the litter boxes and fill with fresh litter"
      data:
        push:
          category: "chore"
        action_data:
          entity_id: input_boolean.chore_cycle_litter_boxes
