alias: "Chore: Cycle Litter Boxes: Reset"
initial_state: true
trigger:
  - platform: time
    at: "07:55:00" # So that cleaning the litter boxes can cascade from this chore
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: on
  - condition: template
    value_template: "{{ (((now().strftime('%W') | int) + 1) % 2) }}" # Even week of year
  - condition: template
    value_template: "{{ (now().isoweekday() == 7) }}" # Sunday
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_cycle_litter_boxes
  - service: notify.slack_standard
    data:
      message: "The chore 'Cycle Litter Boxes' is due today"
