alias: "Notification: Nest Protect: Carbon Monoxide Status Change: Attic Bedroom"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.attic_bedroom_nest_protect_co_status
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: on
action:
  - service: notify.slack_crit
    data:
      message: "Attic Bedroom Nest Protect carbon monoxide status changed to '{{ states.sensor.attic_bedroom_nest_protect_co_status.state }}'"
