alias: "Notification: Nest Protect: Carbon Monoxide Status Change: Entryway"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.entryway_nest_protect_co_status
action:
  - service: notify.slack
    data:
      message: "Entryway Nest Protect carbon monoxide status changed to '{{ states.sensor.entryway_nest_protect_co_status.state }}'"
      target:
        - '#fox-hollow-ha'
        - '#fox-hollow-ha-crit'
