alias: "Notification: Nest Protect: Master Bedroom: Carbon Monoxide Status Change"
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.nest_protect_master_bedroom_co_status
condition:
  - condition: state
    entity_id: input_boolean.automation_slack_notifications
    state: on
action:
  - service: notify.slack_crit
    data:
      message: "Nest Protect: Master Bedroom: Carbon monoxide status changed to '{{ states.sensor.nest_protect_master_bedroom_co_status.state }}'"
