alias: "Chore: Clean Litter Boxes: Input Changed"
initial_state: true
trigger:
  - platform: state
    entity_id: input_boolean.chore_clean_litter_boxes
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: on
  - condition: template
    value_template: "{{ (states.input_boolean.chore_clean_litter_boxes.state == 'off') }}"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_clean_litter_boxes
  - service: notify.ios_parents
    data:
      title: "Chore: Clean Litter Boxes"
      message: "The litter boxes have been cleaned"
  - service: notify.slack_standard
    data:
      message: "The chore 'Clean Litter Boxes' has been completed"
