alias: "Chore: Clean Litter Boxes: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "17:00:00"
  - platform: time
    at: "18:00:00"
  - platform: time
    at: "19:00:00"
condition:
  - condition: state
    entity_id: binary_sensor.automation_chores
    state: "on"
  - condition: template
    value_template: "{{ (states.input_boolean.chore_clean_litter_boxes.state == 'on') }}"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_clean_litter_boxes
  - service: persistent_notification.create
    data:
      title: "Chore: Clean Litter Boxes"
      message: "Clean the litter boxes of pee and poo"
      notification_id: chore_clean_litter_boxes
  - service: notify.ios_parents
    data_template:
      title: "Chore: Clean Litter Boxes"
      message: "Clean the litter boxes of pee and poo"
      data:
        push:
          category: chore
        action_data:
          entity_id: input_boolean.chore_clean_litter_boxes
