alias: "Chore: Clean Litter Boxes: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "17:00:00"
  - platform: time
    at: "18:00:00"
  - platform: time
    at: "19:00:00"
condition:
  condition: and
  conditions:
  - condition: template
    value_template: "{{ states.input_boolean.chore_clean_litter_boxes.state == 'on' }}"
action:
  - service: notify.ios_parents
    data_template:
      title: "Chore: Clean Litter Boxes"
      message: "Clean the litter boxes of pee and poo"
      data:
        actions:
        - action: CHORE_CLEAN_LITTER_BOXES_DONE
          title: Done
        - action: CHORE_CLEAN_LITTER_BOXES_REMIND_LATER
          title: Remind Me Later
