alias: "Chore: Clean Litter Boxes: Reset"
initial_state: true
trigger:
  - platform: time
    at: "08:00:00"
condition: and
  - condition: template
    value_template: "{{ (states.input_boolean.chore_cycle_litter_boxes.state == 'off') }}"
  - condition: and
    conditions: or
      - condition: template
        value_template: "{{ (now().isoweekday() == 3) }}" # Wednesday
      - condition: template
        value_template: "{{ (now().isoweekday() == 7) }}" # Sunday
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_clean_litter_boxes
