---

alias: "Chore: Update Valuable Asset Values: Notification Touched Done"
initial_state: true
trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: CHORE_DONE
      actionData:
        entity_id: input_boolean.chore_update_valuable_asset_values
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.chore_update_valuable_asset_values
