---

alias: "Birthday: Person 9: Tomorrow"
initial_state: true
trigger:
  - platform: time
    at: "09:00:00"
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.automation_milestones
    state: "on"
  - condition: template
    value_template: "{{ (states('input_datetime.birthday_person_9').split('-')[1:] == ((as_timestamp(now()) + 86400) | timestamp_custom('%m-%d')).split('-')) }}"
action:
  - service: notify.mobile_app_parents
    data:
      title: "Birthday: {{ state_attr('input_datetime.birthday_person_9', 'friendly_name') }}: Tomorrow"
      message: "{{ state_attr('input_datetime.birthday_person_9', 'friendly_name') }}'s birthday is tomorrow!"
  - service: notify.slack_standard
    data:
      message: "{{ state_attr('input_datetime.birthday_person_9', 'friendly_name') }}'s birthday is tomorrow!"
