alias: "Chore: Renew Home SSL Certificate: Notification Touched Done"
initial_state: true
trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: CHORE_DONE
      actionData:
        entity_id: input_boolean.chore_renew_home_ssl_certificate
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.chore_renew_home_ssl_certificate
