alias: "Chore: Renew Home SSL Certificate: Reset"
initial_state: true
trigger:
  - platform: time
    at: "06:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: template
    value_template: "{{ (((now().strftime('%j') | int) % 75) == 0) }}" # Every 75 days
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_renew_home_ssl_certificate
  - service: notify.slack_standard
    data:
      message: "The chore 'Renew Home SSL Certificate' is due today"
