alias: "Chore: Run Shredder Lubricant: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "12:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: state
    entity_id: input_boolean.chore_run_shredder_lubricant
    state: "on"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_run_shredder_lubricant
  - service: persistent_notification.create
    data:
      title: "Chore: Run Shredder Lubricant"
      message: "Run a lubricant sheet through the shredder"
      notification_id: chore_run_shredder_lubricant
  - service: notify.ios_parents
    data_template:
      title: "Chore: Run Shredder Lubricant"
      message: "Run a lubricant sheet through the shredder"
      data:
        push:
          category: chore
        action_data:
          entity_id: input_boolean.chore_run_shredder_lubricant
