alias: "Anniversary: Event 4: Tomorrow"
initial_state: true
trigger:
  - platform: time
    at: "09:00:00"
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.automation_milestones
    state: on
  - condition: template
    value_template: "{{ (states.input_datetime.anniversary_4.state.split('-')[1:] == ((as_timestamp(now()) + 86400) | timestamp_custom('%m-%d')).split('-')) }}"
action:
  - service: notify.mobile_app_parents
    data:
      title: "Anniversary: {{ states.input_datetime.anniversary_4.attributes.friendly_name }}: Tomorrow"
      message: "{{ states.input_datetime.anniversary_4.attributes.friendly_name }} anniversary is tomorrow!"
  - service: notify.slack_standard
    data:
      message: "{{ states.input_datetime.anniversary_4.attributes.friendly_name }} anniversary is tomorrow!"
