alias: "Chore: Take Bins To Curb: Reminders"
initial_state: true
trigger:
  - platform: time
    at: "17:00:00"
  - platform: time
    at: "17:30:00"
  - platform: time
    at: "18:00:00"
  - platform: time
    at: "18:30:00"
  - platform: time
    at: "19:00:00"
  - platform: time
    at: "19:30:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: on
  - condition: state
    entity_id: input_boolean.chore_take_bins_to_curb
    state: on
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_take_bins_to_curb
  - service: persistent_notification.create
    data:
      title: "Chore: Take Bins To Curb"
      message: "Take the yard debris, recycling, glass, and trash bins to the curb"
      notification_id: chore_take_bins_to_curb
  - service: notify.mobile_app_parents
    data_template:
      title: "Chore: Take Bins To Curb"
      message: "Take the yard debris, recycling, glass, and trash bins to the curb"
      data:
        push:
          category: chore
        action_data:
          entity_id: input_boolean.chore_take_bins_to_curb
