alias: "Chore: Take Bins To Curb: Reset"
initial_state: true
trigger:
  - platform: time
    at: "06:00:00"
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
action:
  # This chore is timed by a third party, so if we fail to meet their schedule, we miss our window and just wait for next time
  - service: input_boolean.turn_off
    entity_id: input_boolean.chore_take_bins_to_curb
  - service: persistent_notification.dismiss
    data:
      notification_id: chore_take_bins_to_curb
  - condition: template
    value_template: "{{ (now().isoweekday() == 3) }}" # Wednesday
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_take_bins_to_curb
  - service: notify.slack_standard
    data:
      message: "The chore 'Take Bins To Curb' is due today"
