alias: "Chore: Sort Synced Photos On NAS: Reset"
initial_state: true
trigger:
  - platform: time
    at: "08:00:00"
condition:
  - condition: template
    value_template: "{{ (now().day == 10) }}" # Tenth day of month
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_sort_synced_photos_on_nas
  - service: notify.slack_standard
    data:
      message: "The chore 'Sort Synced Photos On NAS' is due today"
