alias: "Notification: Arlo: Camera Battery Level Change: Exterior Front"
initial_state: true
trigger:
  - platform: template
    value_template: "{{ ((states.sensor.battery_level_exterior_front.state | int) < 10) }}"
condition:
  - condition: state
    entity_id: binary_sensor.automation_slack_notifications
    state: "on"
action:
  - service: notify.slack_crit
    data:
      message: "Arlo Exterior Front Camera battery level is less than 10%: {{ states.sensor.battery_level_exterior_front.state }}%"
