---

group.system:
  order: 1
group.alarms:
  order: 2
group.family_presence:
  order: 3
group.security:
  order: 4
group.lights:
  order: 5
group.switches:
  order: 6
# group.weather_snapshot:
#   order: 7
