alias: "Chore: Update Valuable Asset Values: Reset"
initial_state: true
trigger:
  - platform: time
    at: "08:00:00"
condition:
  - condition: state
    entity_id: input_boolean.automation_chores
    state: "on"
  - condition: template
    value_template: "{{ (now().month == 1) }}" # January
  - condition: template
    value_template: "{{ (now().day == 1) }}" # 1st day of month
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chore_update_valuable_asset_values
  - service: notify.slack_standard
    data:
      message: "The chore 'Update Valuable Asset Values' is due today"
